AlluIoT/models.py
#models.py
from AlluIoT import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):

    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key=True)
    profile_image = db.Column(db.String(64),nullable=False,default='default_profile.jpg')
    email = db.Column(db.String(64),unique=True,index=True)
    username = db.Column(db.String(64),unique=True,index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost',backref='author',lazy=True)

    def __init__(self,email,username,password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f"Username {self.username}"


class BlogPost(db.Model):

    users = db.relationship(User)

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)

    date = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    title = db.Column(db.String(140),nullable=False)
    text = db.Column(db.Text,nullable=False)

    def __init__(self,title,text,user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID: {self.id} -- Date: {self.date} --- {self.title}"

AlluIoT/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField,FileAllowed

from flask_login import current_user
from AlluIoT.models import User

class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('UserName',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password',validators=[DataRequired()])
    submit = SubmitField('Register!')

    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')


class UpdateUserForm(FlaskForm):

    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('UserName',validators=[DataRequired()])
    picture = FileField('Update Profile Picture',validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')

AlluIoT/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from . import comp_dash
from . import instant_dash
from . import table_dash
from . import pump_dash

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecret'

instantDash = instant_dash.Add_Dash(app)
compDash = comp_dash.Add_Dash(app)
tableDash = table_dash.Add_Dash(app)
pumpDash = pump_dash.Add_Dash(app)

### for SQLite ###################################
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

### For PostgresSQL #############################
# POSTGRES = {
#     'user': 'postgres',
#     'pw': 'postgres',
#     'db': 'allu_iot',
#     'host': 'localhost',
#     'port': '5432',
# }
# app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://%(user)s:\
# %(pw)s@%(host)s:%(port)s/%(db)s' % POSTGRES
# app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

###### END DATABASE SETUP ######

###### LOGIN SETUP #############
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

###### END LOGIN SETUP #########

###### BLUEPRINTs SETUP #############

from AlluIoT.core.views import core
from AlluIoT.users.views import users
from AlluIoT.error_pages.handlers import error_pages


app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(error_pages)


###### END BLUEPRINTs SETUP #########

AlluIoT/core/views.py
from flask import render_template, request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

@core.route('/instView_dash')
def instView_dash():
    return render_template('instView_dash.html')

@core.route('/compareView_dash')
def compareView_dash():
    return render_template('compareView_dash.html')

@core.route('/pumpView_dash')
def pumpView_dash():
    return render_template('pumpView_dash.html')

@core.route('/tableView_dash')
def tableView_dash():
    return render_template('tableView_dash.html')

AlluIoT/users/views.py
# users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from AlluIoT import db
from AlluIoT.models import User, BlogPost
from AlluIoT.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from AlluIoT.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.info')

            return redirect(next)

    return render_template('login.html',form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)











# user's list of Blog posts

AlluIoT/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{current_user.username}}</h1>
      <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
    </div>
  </div>

  <div class="container">
    <form  method="POST" action="" enctype="multipart/form-data"> 
        {{form.hidden_tag()}}
      <div class="form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
      </div>
    
      <div class="form-group">
      {{form.email.label(class='form-group')}}
      {{form.email(class='form-control')}}
      </div>

      <div class="form-group">
      {{form.picture.label(class='form-group')}}
      {{form.picture(class='form-control')}}
      </div>

      <div class="form-group">
       {{form.submit(class='btn btn-primary')}}
      </div>


    </form>
  </div>

{% endblock %}

AlluIoT/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="HandheldFriendly" content="true" />

    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="static/css/main.css" />

    <title>Python Data Scinece Web Environment</title>
  </head>

  <body>
    <!-- ################## content START here ############################ -->


  <div class="overlay">
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
 
 <!-- Navbar brand -->
    <a class="navbar-brand" href="#">
    <img src="static/images/ML_python.png" alt="Logo">PyML</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">


      {% if current_user.is_authenticated %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          DASHBOARDS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{url_for('core.instView_dash')}}">Dashboard Instantâneo (m3 & Volt)</a>
          <a class="dropdown-item" href="{{url_for('core.compareView_dash')}}">Dashboard Comparativo (m3)</a>
          <a class="dropdown-item" href="{{url_for('core.tableView_dash')}}">Dashboard Individual (m3)</a>
          <a class="dropdown-item" href="{{url_for('core.pumpView_dash')}}">Dashboard Bombas (Volt)</a>
        </div>
      </li>

        <li class='nav-link'>
          <a href="{{url_for('users.account')}}">Account</a>
        </li>

        <li class='nav-link'>
          <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>

      {% else %}

          <li class='nav-link'>
            <a href="{{url_for('users.login')}}">Log In</a>
          </li>
          <li class='nav-link'>
            <a href="{{url_for('users.register')}}">Register</a>
          </li>
      {% endif %}


      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">About</a>
      </li>

      <li class='nav-link active'>  
        <a href="{{url_for('core.index')}}">Home <span class="sr-only">(current)</span></a>
      </li>

      </ul>
    </div>
  </nav>

  <div style="height: 100vh;background:transparent;padding-top: 20px" class='container-fluid'>
    {% block content %}

    {% endblock %}
  </div>

</div>



    <!-- ################## content END here ############################## -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript" src='static/scripts/main.js'></script>
  </body>
</html>

AlluIoT/templates/base_bkp.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!--
    <link href="static/bootstrap4_2_1/css/bootstrap.min.css" rel="stylesheet">
    <script src="static/bootstrap4_2_1/js/bootstrap.min.js"></script>
    <script src="static/bootstrap4_2_1/scripts/jquery-3.3.1.min.js"></script>
    <script src="static/bootstrap4_2_1/scripts/popper.min.js"></script>
    <link href="static/custom-css/main.css" rel="stylesheet" type="text/css">
-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" type="text/css" href="static/custom-css/main.css" />
    <script type="text/javascript" src="static/scripts/main.js"></script>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="HandheldFriendly" content="true" />
    <title>Allu_IoT</title>
  </head>

  <body>
    <!--
<header class="header">
  <div class="overlay">
    </div>
</header>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding-bottom: 10px">  

            data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"

class="navbar navbar-inverse bg-inverse navbar-toggleable-sm navbar-expand-lg"

-->
    <header class="header">
      <div class="overlay">
        <nav
          class="navbar navbar-inverse bg-inverse navbar-toggleable-sm navbar-expand-lg"
          style="background:#ADD8E6"
        >
          <a class="navbar-brand" href="#">
            <img src="static/images/AlluIoT_logo.jpg" style="display:
            inline-block; width: 50px; height: 100%;>
            <span style="display: inline-block;"> AlluIoT</span>
          </a>

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              {% if current_user.is_authenticated %}

              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  style="color:rgba(236, 119, 24, 0.931)"
                >
                  DASHBOARDS
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a
                    class="dropdown-item"
                    href="{{ url_for('core.instView_dash') }}"
                    >Dashboard Instantâneo (m3 & Volt)</a
                  >
                  <a
                    class="dropdown-item"
                    href="{{ url_for('core.compareView_dash') }}"
                    >Dashboard Comparativo (m3)</a
                  >
                  <a
                    class="dropdown-item"
                    href="{{ url_for('core.tableView_dash') }}"
                    >Dashboard Individual (m3)</a
                  >
                  <a
                    class="dropdown-item"
                    href="{{ url_for('core.pumpView_dash') }}"
                    >Dashboard Bombas (Volt)</a
                  >
                </div>
              </li>

              <li class="nav-link">
                <a href="{{ url_for('users.account') }}">Account</a>
              </li>

              <li class="nav-link">
                <a href="{{ url_for('users.logout') }}">Log Out</a>
              </li>

              {% else %}

              <li class="nav-link">
                <a href="{{ url_for('users.login') }}">Log In</a>
              </li>
              <li class="nav-link">
                <a href="{{ url_for('users.register') }}">Register</a>
              </li>
              {% endif %}

              <li class="nav-link">
                <a href="{{ url_for('core.info') }}">About</a>
              </li>

              <li class="nav-link active">
                <a href="{{ url_for('core.index') }}"
                  >Home <span class="sr-only">(current)</span></a
                >
              </li>
            </ul>
          </div>
        </nav>

        <div
          style="height: 100vh;background:transparent;padding-top: 20px"
          class="container-fluid"
        >
          {% block content %} {% endblock %}
        </div>
      </div>
    </header>
  </body>
</html>

AlluIoT/templates/compareView_dash.html
{% extends "base.html" %} {% block content %}

<div style="position:relative;height:100%;overflow:hidden;padding-top:56.25%">
  <iframe
    style="position:absolute; top:0; left:0; width:100%; height:100%; border:0"
    src="https://pymldash.herokuapp.com/comp_dash"
  ></iframe>
</div>

<!--
comments go here
-->
{% endblock %}

AlluIoT/templates/index.html
{% extends "base.html" %}
{% block content %}


<!-- About -->

<div class="container">
    
    <div class="row">
      <div class="col-lg-12 text-center">
      <h2>Wellcome</h2>
      <hr class="star-primary">
      </div>
    </div>
    <div class="row">
        <div class="col-lg-12 text-center">
        <h3>Please Log In to visit our dashboards</h3>
 
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 text-center">
        <h2></h2>
        </div>
      </div>

    <div class="row">
      <div class="col-lg-4">
       <img src="static/images/pfdc_jpeg.jpg" class="img-responsive" alt="">
      </div>
      <div class="col-lg-8">
        <p><strong>Python Machine Learning for IoT </strong><br>
          <small>A WEB application to easily create IoT ML applications</small><br></p>
        
        <div class="progress">
        <div class="progress-bar progress-bar-success" style="width: 55%">
          <span class="sr-only">55% Complete (success)</span>55% achieved
        </div>
        <div class="progress-bar progress-bar-info" style="width: 45%">
          <span class="sr-only">45% Complete (warning)</span>45% to go
        </div>
      </div>
        
        <p><strong>A mobile friendly Web environment</strong> for building machine learning applications and 
            <strong>easily post their graphical insights to the Web</strong></p>
            <p>This tool takes advatage of the following technologies:</p>
            <ul>
                <li>Flask, React and Bootstrap for responsive web framework </li>  
                <li>Pandas, NumPy and SciKit for crunching IoT data series information</li>
                <li>Python REST APIs and DB connectors to explore any Time Series Database</li>
                <li>Plotly-Dash to easily build dynamyc and interactive dashboards</li> 
             </ul>
          </div>
    </div>
    
</div>
{% endblock %}

AlluIoT/templates/info.html
{% extends "base.html" %}
{% block content %}


<!-- About -->

<div class="container">
    
  <div class="row">
    <div class="col-lg-12 text-center">
    <h2>Congratulations !</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 text-center">
    <h2>You have successfully logged in </h2>
    <hr class="star-primary">
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-4">
      <img src="static/images/plotly-dash.jpg" class="img-responsive" alt="">
    </div>
    <div class="col-lg-8">
      <p><strong>Please use the top NabBar to explore our dashboards </strong></p>
      <p>Our Web App seamlessly integrates the Plotly-Dash interactive dashboard framework</p>
    </div>
  </div>
    
</div>
{% endblock %}

AlluIoT/templates/instView_dash.html
{% extends "base.html" %} {% block content %}

<div
  style="padding:40px; width: 100%; height: 100%; min-height: 100%;"
  class="container"
>
  <iframe
    style="width: 100%; height: 100%; border: none; margin: 0; padding: 0;"
    src="https://pymldash.herokuapp.com/instant_dash"
  ></iframe>
</div>

{% endblock %}

AlluIoT/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form method="POST">
    {{form.hidden_tag()}}
  
    <div class="form-group">
    {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
    </div>

    <div class="form-group">
    {{form.password.label(class='form-group')}}{{form.password(class='form-control')}}
    </div>

    <div class="form-group">
    {{form.submit(class='btn btn-primary')}}
    </div>
  
  </form>
</div>
{% endblock %}

AlluIoT/templates/pumpView_dash.html
{% extends "base.html" %} {% block content %}

<div
  style="padding:40px; width: 100%; height: 100%; min-height: 100%;"
  class="container"
>
  <iframe
    style="width: 100%; height: 100%; border: none; margin: 0; padding: 0;"
    src="https://pymldash.herokuapp.com/pump_dash"
  ></iframe>
</div>

<!--
<p> OK </p>
-->
{% endblock %}

AlluIoT/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
    {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
    </div>  
    <div class="form-group">
    {{form.username.label(class='form-group')}}{{form.username(class='form-control')}}
    </div>  
    <div class="form-group">
    {{form.password.label(class='form-group')}}{{form.password(class='form-control')}}
    </div>  
    <div class="form-group">
    {{form.pass_confirm.label(class='form-group')}}{{form.pass_confirm(class='form-control')}}
    </div>  
    <div class="form-group">
    {{form.submit(class='btn btn-primary')}}
    </div>  
  
  </form>
</div>
{% endblock %}

AlluIoT/templates/tableView_dash.html
{% extends "base.html" %} {% block content %}

<div
  style="padding:40px; width: 100%; height: 100%; min-height: 100%;"
  class="container"
>
  <iframe
    style="width: 100%; height: 100%; border: none; margin: 0; padding: 0;"
    src="https://pymldash.herokuapp.com/tab_dash"
  ></iframe>
</div>

<!--
<p> OK </p>
-->
{% endblock %}

AlluIoT/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{user.username}}</h1>
      <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" >
    </div>
  </div>


{% for post in blog_post.items  %}
  <h2> <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a> </h2>
  Written By: <a href="{{url_for('users.user_post',username=post.author.username)}}">{{post.author.username}}</a>
  <p class='text-muted'>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
   <br>
   <p>{{post.text}}</p>
   <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
      {% if blog_posts.page == page_num %}
      <li class='page-item disabled'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% else %}
      <li class='page-item'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>

</nav>




{% endblock %}